### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by weaselonfire** [muhamed89/MIUI#1040]
Hi,

I followed the link on xiaomi.eu and like to report the following bug for the weekly ROM 6.12.15 on a Redmi 4 Prime.
In german language the settings app crashes when you go to Settings->Advanced->Buttons showing this error report:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
    at android.app.ActivityThread.access$900(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
    at android.os.Handler.dispatchMessage(Handler.java)
    at android.os.Looper.loop(Looper.java)
    at android.app.ActivityThread.main(ActivityThread.java)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.remove(ArrayList.java:403)
    at com.android.settings.KeySettings.onCreate(KeySettings.java)
    at android.app.Fragment.performCreate(Fragment.java)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
    at android.app.BackStackRecord.run(BackStackRecord.java)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
    at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java)
    at com.android.settings.hw.a(SettingsActivity.java)
    at com.android.settings.hw.onCreate(SettingsActivity.java)
    at android.app.Activity.performCreate(Activity.java)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
    ... 10 more

**Comment by berlinux2016** [comment]
This will be fixed next friday release.
